include:
  - project: "development/sec-templates"
    ref: "charles.mgema-main-patch-48059"
    file: "/.gitlab-ci-sonarqube-template.yml"

stages:
  - publish

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

build_docker_image:
  stage: publish
  tags:
    - shell
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - DOCKER_BUILDKIT=1 docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST