version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8069:8069"
    #   - "5678:5678" # debugpy port
    # command: >
    #   /usr/bin/python3 -m debugpy --listen 0.0.0.0:5678 --wait-for-client /usr/bin/odoo
    #   --config=/etc/odoo/odoo.conf

    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./custom-addons:/mnt/extra-addons/custom-addons
      - ./enterprise-addons:/mnt/extra-addons/enterprise-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data:
