# Copyright (C) 2025 Metzler IT GmbH
# License Odoo Proprietary License v1.0 (OPL-1)
# You may use this file only in accordance with the license terms.
# For more information, visit:
# https://www.odoo.com/documentation/19.0/legal/licenses/licenses.html#odoo-proprietary-license

"""MailDesk Attachment.

Defines domain concepts used by MailDesk (Attachment).
Layer: domain.
"""

from dataclasses import dataclass
from typing import Optional


@dataclass(frozen=True)
class Attachment:
    """
    Canonical representation of an email attachment.
    This contract is provider-agnostic.
    """

    # Identifiers
    id: str  # Opaque identifier for retrieval (not necessarily provider ID)
    name: str  # Filename with extension

    # Content Metadata
    mimetype: str
    size: int  # Bytes

    # Inline Display
    is_inline: bool = False
    content_id: Optional[str] = None  # Content-ID header for inline references (CID)

    # Retrieval
    # URLs are generated by the use-case layer, but carried here for UI convenience.
    preview_url: Optional[str] = None
    download_url: Optional[str] = None
