{
    "name": "Enhanced Helpdesk",
    "version": "19.0.1.0.0",
    "summary": "Enhanced Helpdesk Functionality",
    "description": "Adds extended features to the Helpdesk module.",
    "category": "Services/Helpdesk",
    "author": "ictpack",
    "license": "LGPL-3",
    "depends": ["base", "helpdesk"],
    "data": [
        "security/ir.model.access.csv",
        "data/helpdesk_working_time_data.xml",
        "views/reasons_to_hold_ticket_menu.xml",
        "reports/ticket_report_template.xml",
        "reports/ticket_report_action.xml",
        "views/helpdesk_ticket_form.xml",
        "views/helpdesk_working_time_views.xml",
        "views/helpdesk_working_time_wizard_views.xml",
        "views/helpdesk_ticket_views.xml",
        "views/helpdesk_ticket_tag_transfer_views.xml",
        "views/helpdesk_transfer_wizard_views.xml",
        "views/helpdesk_hold_wizard_views.xml",
        "views/helpdesk_hold_confirmation_wizard_views.xml",
        "wizard/helpdesk_transfer_close_wizard_views.xml",
        "data/helpdesk_hold_reasons_data.xml",
        "data/helpdesk_rejection_reasons_data.xml",
        'data/bussines_line.xml',
       "data/email_template_sla_breach.xml",
        "data/ir_cron.xml",
        'views/helpdesk_tag_views.xml',
        'views/helpdesk_tagged_team_analysis_views.xml',
        'views/helpdesk_hold_analysis_views.xml',
        'views/helpdesk_hold_status_count_analysis_views.xml',
        'views/helpdesk_analysis_dashboard.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'enhanced_helpdesk/static/src/js/hold_wizard.js',
            'enhanced_helpdesk/static/src/css/hold_wizard.css',
        ],
    },
    "installable": True,
    "application": False,
    "auto_install": False,
}
